dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
git:
  depth: 3
cache:
  directories:
  - "$HOME/.m2"
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
- ln -sfT ${PWD}/target/travis-settings/settings.xml ${HOME}/.m2/settings.xml
- ln -sfT ${PWD}/target/travis-settings/mvnw mvnw
- ln -sft ${PWD} ${PWD}/target/travis-settings/.mvn
install: "${PWD}/target/travis-settings/java/install.sh"
script: "${PWD}/target/travis-settings/java/script.sh"
after_success: "${PWD}/target/travis-settings/java/after_success.sh"
env:
  global:
  - secure: h5Ecm9AY4qCtLrUn1xBxvmrqbsaaalh69xvQLLpvGIE1lvAgxZFA3KXhiKqspJhzjE/Kf7VVO6peaw3xWMCNOA7/dUBstkRmmiNICjFyX+1Q/sVYARlBk1zOMK4PGVUk0o39cvxXimLHUzCweYpWqZhj+ZZ5Uohdqtg7y/whibe4l1+IoKxQk25s8MF8vwl1RBOpWhMgA1ciYlgQIyFaSOTpjk3C6cta3dBp9JC+ZpXX9D28PKw7bdl3V8L/AWjo8zLrYdhFmjZ490RCf8g+/H7o+qAe7e6hQ6XhRleXOCQ04/NCKxBbqZFN6KGaXDk42CR7EEJzRfeCkJJHzaeZ3Su2FquZCVmNEvio25mjcryfasvw5PYz3zwbuYCwx2QXDUZObXEaph8hzZWscKd6sc02U7x7AfBd+Qx6s4jG5VcBY1sh9MlYVkkKiggTIzbfYzm7w3YqcgGi4jV9g6XnFTCIkZafCNRomypxRh8N/Vj51p6UokqcKPTLzfflIYRSbZ/kJO7j1tcrVHNLtZ0JS3ZUBz68U8xA0dB5omtdRDDwDObSK8pEefpN5x8LRt9oCh8GXr+wJfB34hp4dsKVD0/s83YZRUw2wcMvonmGvgvtAd+i5bVscsigUlJbIiDkNC9p1G/ZMLpmjmfB9PRGhtY15318DDrfDGWg+SFu1bs=
  - secure: MshVpIL8UaSlqaBlSq05C+5ahvdnOJY0hAXXuG03EVzFvVyFtm6nfQ5b6e8Q23VVUW2UI0NqFXF9sqcxGCoNYiKL70RE8JoIyfQX9KqzYBXfTNKZbAxJjaXiRlmsnctpPLy4iiQxbX7Rr1E2dHa2omZh/DO+7z6+CdqaNjMDon4Nu5QH/qcYu26BbXBmplYVncpUSbzDDeGgSgIfhqVHLwAMbWWvutW5QGGw/6Gs/n1uiz2PYXja1Xr1OWtX1zcxJwELQUUEOk4M1h7DHGzoMvoEPpdH1OQOWabKX4LnwklLgMMKhN68c3NBTZtNVTOAwHMnpJnoW7mqXXmnLuw13AtcbuO0fTnC/r2dnrgfV/H2bLzBpyrqwYGYWtgDKDQr2/WLe4Ljs4s5RTBOM/stJXG18yusCHbfretVBEuLJgqG7pJ+2s/oArU7mBW5P3INzF8jIcj0BlJan01VqmHR4nT6kdm+fVGQam2jZaMtp2hnVp7AYDy7vN+E2sJp7mue064UEupk2OFLHwoXi1bxn5IppJAU0lD9Ki8KgOG6MZbRb365CYH52Aj04Jp+Y//uAqy7UHycBEbeayR219oSe3uZq5MlNl3BInVgavJFpLTNwkatG99G/D93+h888aPXPoi9Ej00vl08h1dIjLYKyXGvQvL08hKJuNkwNcay/Fs=
