---
dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
git:
  depth: 3
cache:
  directories:
  - "$HOME/.m2"
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
- ln -sfT ${PWD}/target/travis-settings/settings.xml ${HOME}/.m2/settings.xml
install: ${PWD}/target/travis-settings/java/install.sh
script: ${PWD}/target/travis-settings/java/script.sh
after_success: ${PWD}/target/travis-settings/java/after_success.sh
env:
  global:
  - secure: Pcc28hVovVV6EddArNm0q5dxOztPHYLFzj+IcMQeHv/KiQBTP9EMfJMFzyTqgU+lIijJVDFqSRNb/HXpfSgJz27bcWc28gUpyBy6M460FJPzM1DG67nytr5J9288UgPHPeZnM+qGQ5kIUR6Lo1+EdRbYcGEfUDQHYUp/d19KrbJO4TGsygFGW5oSL5qxof7w9x+cuAWgVXQ0Rrrz0k3lDU9vRkQclpKAHMvAONMJcMeXK4SAkS6TEM+WE5H7NLHPJ0MS0LiA/6nRVjRdUZEAy/+OX/IDyNDp/log0pVtPiLnVNmfqdRM+Rjg6DvHuswYwRTAB9Ef2WUn3bXDNpomZsIW8LWXXQ9qMLS/3ng7Fd/pqGV8AWvLIBLb70+A9nZ1Xvimws5W89eqgz2ZiYSwYJn0Pvy+hZkBtLgwMLFq2/DiwK1XqObqdub8LDGqaEmNZ7tGmKTvIWSZKbk2UO/coQhWXy9Ed/9Ycu5pZYPo97XookVgFAh6DAIeHKrUOM5SeShEbQXfV0O/+ZPT8IX7GqfAYv4tOSVGa35OmY1mr4P++uYhW4OCqGhLNwjzKnf1T6Bi8a/ybFII1zcoCYlXe6wYyMuJ7U88Y91u2l03rAcATp2mfQJ54jp3jau3XK1D05II2zBkwvXRf+zCmfcFOVD3XXF+B+hmgTITq8caHps=
  - secure: wacKv5jjl4VnkUl6Jua8NoyRLvNAOSjVXg/vF2WwLJRA3W8NEDHikBdFf2Ew/Nb/FZcIb5gwHgl1whTRiHDQXm70+Qk7h9RObetb+T6JYy1P0jb9ZpHCQEUW62YrgMNNtnt09WS1bObQ2OnVxAX9YilDbHETr2zn9Ww3DrR4cmOMwh3tbcFyIKhslmRCVHOUy6OyrXcrS1ZenUc+afip0zvdyAYUdaplzfuZdu5MKt0A/frZILhqMD6c5QOJuI+DTxHFnjbLE+cA0jyLtLDV2LfkBep677YkHpRXTqmZ8rzdgrTpSYDh3zjaLnCPqIC6P/Gh9Z1mcgBF/gE43nNvTPOidgZnd2ips1pxRh7JKK7APEAfrOEUCAsh9ADrZiCKrrhMY4X5r9hQwY5QD1jpejKeg4KJMzdHlKnDwYTXO8TP0flkLp0BwTZ+NdEMSeBbQIn1IMBh9yXA07nSICBEJ+V0qsYPXOQaJ9s/ailXGG0bOO6EGfbqn3U3xzvU4WkGt4Ca7a5uTRLZm3xEIbwN4XZJvxKFM4v/4ANuR3vXV6qBC2H8yEVOuJpdXZ8z1CmIOf5tCU2Hf75e+LUrLxBL5Ip/JggOZBlnzPcIZy6QCegDf283H1vKqMF8d1EpJXlUaiVecZ+sCK8KQrSOwZLtxmqASpic3NXn1S5GxFfZ9Ys=
